routes/web.php
<?php

use App\Http\Controllers\AddressController;
use App\Http\Controllers\EmployeeController;
use App\Http\Controllers\TrashController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::middleware(['auth','admin'])->group(function(){
    Route::get('employees/create-basic',[EmployeeController::class,'create_basic'])->name('employees.create-basic');
    Route::get('employees/create-address',[EmployeeController::class,'create_address'])->name('employees.create-address');
    Route::get('employees/create-post',[EmployeeController::class,'create_post'])->name('employees.create-post');

    Route::post('employees/store-basic',[EmployeeController::class,'store_basic'])->name('employees.store-basic');
    Route::post('employees/store-address',[EmployeeController::class,'store_address'])->name('employees.store-address');
    Route::resource('employees', EmployeeController::class)->except('create');
    Route::get('trashes/pending', [TrashController::class,'adminPending'])->name('trashes.pending');
    Route::put('trashes/assign/{trash}', [TrashController::class,'adminAssign'])->name('trashes.assign');
});
Route::middleware(['auth','employee'])->group(function(){
    Route::get('trashes/assigned',[TrashController::class,'assigned'])->name('trashes.assigned');
    Route::put('trashes/picked/{trash}',[TrashController::class,'picked'])->name('trashes.picked');
    Route::put('trashes/reject/{trash}',[TrashController::class,'reject'])->name('trashes.reject');
});
Route::middleware(['auth'])->group(function(){

    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
    Route::resource('trashes', TrashController::class);
    Route::resource('addresses', AddressController::class);

});

app/Http/Controllers/AddressController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\employee\CreateEmployeeAddressRequest;

use App\Models\Address;
use Illuminate\Http\Request;

class AddressController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $addresses = Address::ofUser()->get();
        return view('address.index',compact('addresses'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('address.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateEmployeeAddressRequest $request)
    {

        Address::create([
            'user_id' => auth()->id(),
            'address' => $request->address,
            'landmark' => $request->landmark,
            'city' => $request->city,
            'district' => $request->district,
            'state' => $request->state,
            'postal_code' => $request->postal_code
        ]);
        return redirect(route('addresses.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Address  $address
     * @return \Illuminate\Http\Response
     */
    public function show(Address $address)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Address  $address
     * @return \Illuminate\Http\Response
     */
    public function edit(Address $address)
    {
        $this->authorize('update',$address);
        return view('address.edit',compact('address'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Address  $address
     * @return \Illuminate\Http\Response
     */
    public function update(CreateEmployeeAddressRequest $request, Address $address)
    {
        $this->authorize('update',$address);
       $address->update([
           'address' => $request->address,
           'landmark' => $request->landmark,
           'city' => $request->city,
           'district' => $request->district,
           'state' => $request->state,
           'postal_code' => $request->postal_code
       ]);
       return redirect(route('addresses.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Address  $address
     * @return \Illuminate\Http\Response
     */
    public function destroy(Address $address)
    {
        $this->authorize('forceDelete',$address);
        $address->delete();
        return redirect(route('addresses.index'));
    }
}

resources/views/address/create.blade.php
@extends('layouts.admin-panel.app')
@section('content')
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Validation</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Create</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <!-- left column -->
          <div class="col-md-12">
            <!-- jquery validation -->
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Create Address
                </h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <form action="{{route('addresses.store')}}" method="POST" id="quickForm">
                @csrf
                @method('POST')
                <div class="card-body">
                    <div class="form-group">
                        <label for="address">Address</label>
                        <textarea name="address" id="address" cols="30" rows="10" class="form-control @error('address') is-invalid @enderror" placeholder="Enter Address" required>{{old('address')}}</textarea>

                        @error('address')
                            <small class="text-danger">{{$message}}</small>
                        @enderror
                    </div>
                    <div class="form-group">

                        <label for="landmark">Landmark</label>
                        <input type="text" name="landmark" class="form-control @error('landmark') is-invalid @enderror" id="landmark" placeholder="Enter Landmark" value="{{old('landmark')}}" required>

                        @error('landmark')
                            <small class="text-danger">{{$message}}</small>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="city">City</label>
                        <input type="text" name="city" class="form-control @error('city') is-invalid @enderror" id="city" placeholder="Enter City"  value="{{old('city')}}" required>
                        @error('city')
                            <small class="text-danger">{{$message}}</small>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="district">District</label>
                        <input type="text" name="district" class="form-control @error('district') is-invalid @enderror" id="district" placeholder="Enter District"  value="{{old('district')}}" required>
                        @error('district')
                            <small class="text-danger">{{$message}}</small>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="state">State</label>
                        <input type="text" name="state" class="form-control @error('state') is-invalid @enderror" id="state" placeholder="Enter State"  value="{{old('state')}}" required>
                        @error('state')
                            <small class="text-danger">{{$message}}</small>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="postal_code">Postal Code</label>
                        <input type="text" name="postal_code" class="form-control @error('postal_code') is-invalid @enderror" id="postal_code" placeholder="Enter Postal Code"  value="{{old('postal_code')}}" required>
                        @error('postal_code')
                            <small class="text-danger">{{$message}}</small>
                        @enderror
                    </div>
                </div>
                <!-- /.card-body -->
                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Next</button>
                </div>
              </form>
            </div>
            <!-- /.card -->
            </div>
          <!--/.col (left) -->
          <!-- right column -->
          <div class="col-md-6">

          </div>
          <!--/.col (right) -->
        </div>
        <!-- /.row -->
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>
@endsection

resources/views/address/edit.blade.php
@extends('layouts.admin-panel.app')
@section('content')
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Validation</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Create</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <!-- left column -->
          <div class="col-md-12">
            <!-- jquery validation -->
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Edit Address
                </h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <form action="{{route('addresses.update',$address->id)}}" method="POST" id="quickForm">
                @csrf
                @method('PUT')
                <div class="card-body">
                    <div class="form-group">
                        <label for="address">Address</label>
                        <textarea name="address" id="address" cols="30" rows="10" class="form-control @error('address') is-invalid @enderror" placeholder="Enter Address" required>{{old('address',$address->address)}}</textarea>

                        @error('address')
                            <small class="text-danger">{{$message}}</small>
                        @enderror
                    </div>
                    <div class="form-group">

                        <label for="landmark">Landmark</label>
                        <input type="text" name="landmark" class="form-control @error('landmark') is-invalid @enderror" id="landmark" placeholder="Enter Landmark" value="{{old('landmark',$address->landmark)}}" required>

                        @error('landmark')
                            <small class="text-danger">{{$message}}</small>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="city">City</label>
                        <input type="text" name="city" class="form-control @error('city') is-invalid @enderror" id="city" placeholder="Enter City"  value="{{old('city',$address->city)}}" required>
                        @error('city')
                            <small class="text-danger">{{$message}}</small>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="district">District</label>
                        <input type="text" name="district" class="form-control @error('district') is-invalid @enderror" id="district" placeholder="Enter District"  value="{{old('district',$address->district)}}" required>
                        @error('district')
                            <small class="text-danger">{{$message}}</small>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="state">State</label>
                        <input type="text" name="state" class="form-control @error('state') is-invalid @enderror" id="state" placeholder="Enter State"  value="{{old('state',$address->state)}}" required>
                        @error('state')
                            <small class="text-danger">{{$message}}</small>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="postal_code">Postal Code</label>
                        <input type="text" name="postal_code" class="form-control @error('postal_code') is-invalid @enderror" id="postal_code" placeholder="Enter Postal Code"  value="{{old('postal_code',$address->postal_code)}}" required>
                        @error('postal_code')
                            <small class="text-danger">{{$message}}</small>
                        @enderror
                    </div>
                </div>
                <!-- /.card-body -->
                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Next</button>
                </div>
              </form>
            </div>
            <!-- /.card -->
            </div>
          <!--/.col (left) -->
          <!-- right column -->
          <div class="col-md-6">

          </div>
          <!--/.col (right) -->
        </div>
        <!-- /.row -->
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>
@endsection

resources/views/address/index.blade.php
@extends('layouts.admin-panel.app')
@section('content')
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Address</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Address</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-12">
            <div class="card">
              <div class="card-header">
                <h3 class="card-title">Details</h3>
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                <table id="example2" class="table table-bordered table-hover">
                  <thead>
                  <tr>
                    <th>Address</th>
                    <th>Landmark</th>
                    <th>City</th>
                    <th>District</th>
                    <th>State</th>
                    <th>Postal Code</th>
                    <th>Actions</th>
                  </tr>
                  </thead>
                  <tbody>
                    @foreach ($addresses as $address)
                        <tr>

                            <td>{{$address->address}}</td>
                            <td>{{$address->landmark}}</td>
                            <td>{{$address->city}}</td>
                            <td>{{$address->district}}</td>
                            <td>{{$address->state}}</td>
                            <td>{{$address->postal_code}}</td>
                            <td><a href="{{route('addresses.edit',$address->id)}}" class="btn btn-warning">Edit</a>
                                <form action="{{route('addresses.destroy',$address->id)}}" method="POST">
                                    @csrf
                                    @method('DELETE')
                                    <button type="submit" class="mt-2 btn btn-danger">Delete</button>
                                </form></td>
                        </tr>
                    @endforeach
                  </tbody>
                </table>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->

          </div>
          <!-- /.col -->
        </div>
        <!-- /.row -->
      </div>
      <!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>
@endsection