routes/web.php
<?php

use App\Http\Controllers\AddressController;
use App\Http\Controllers\EmployeeController;
use App\Http\Controllers\TrashController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::middleware(['auth','admin'])->group(function(){
    Route::get('employees/create-basic',[EmployeeController::class,'create_basic'])->name('employees.create-basic');
    Route::get('employees/create-address',[EmployeeController::class,'create_address'])->name('employees.create-address');
    Route::get('employees/create-post',[EmployeeController::class,'create_post'])->name('employees.create-post');

    Route::post('employees/store-basic',[EmployeeController::class,'store_basic'])->name('employees.store-basic');
    Route::post('employees/store-address',[EmployeeController::class,'store_address'])->name('employees.store-address');
    Route::resource('employees', EmployeeController::class)->except('create');
    Route::get('trashes/pending', [TrashController::class,'adminPending'])->name('trashes.pending');
    Route::put('trashes/assign/{trash}', [TrashController::class,'adminAssign'])->name('trashes.assign');
});
Route::middleware(['auth','employee'])->group(function(){
    Route::get('trashes/assigned',[TrashController::class,'assigned'])->name('trashes.assigned');
    Route::put('trashes/picked/{trash}',[TrashController::class,'picked'])->name('trashes.picked');
    Route::put('trashes/reject/{trash}',[TrashController::class,'reject'])->name('trashes.reject');
});
Route::middleware(['auth'])->group(function(){

    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
    Route::resource('trashes', TrashController::class);
    Route::resource('addresses', AddressController::class);

});

resources/views/layouts/admin-panel/partials/_navbar.blade.php
<!-- Navbar -->
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fa fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="index3.html" class="nav-link">Home</a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="#" class="nav-link">Contact</a>
      </li>
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
      <!-- Navbar Search -->
      <li class="nav-item">
        <a class="nav-link" data-widget="navbar-search" href="#" role="button">
          <i class="fa fa-search"></i>
        </a>
        <div class="navbar-search-block">
          <form class="form-inline">
            <div class="input-group input-group-sm">
              <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
              <div class="input-group-append">
                <button class="btn btn-navbar" type="submit">
                  <i class="fa fa-search"></i>
                </button>
                <button class="btn btn-navbar" type="button" data-widget="navbar-search">
                  <i class="fa fa-times"></i>
                </button>
              </div>
            </div>
          </form>
        </div>
      </li>

      <!-- Messages Dropdown Menu -->
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="fa fa-comments"></i>
          <span class="badge badge-danger navbar-badge">3</span>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img src="{{asset('dist/img/user1-128x128.jpg')}}" alt="User Avatar" class="img-size-50 mr-3 img-circle">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  Brad Diesel
                  <span class="float-right text-sm text-danger"><i class="fa fa-star"></i></span>
                </h3>
                <p class="text-sm">Call me whenever you can...</p>
                <p class="text-sm text-muted"><i class="fa fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img src="{{asset('dist/img/user8-128x128.jpg')}}" alt="User Avatar" class="img-size-50 img-circle mr-3">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  John Pierce
                  <span class="float-right text-sm text-muted"><i class="fa fa-star"></i></span>
                </h3>
                <p class="text-sm">I got your message bro</p>
                <p class="text-sm text-muted"><i class="fa fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img src="{{asset('dist/img/user3-128x128.jpg')}}" alt="User Avatar" class="img-size-50 img-circle mr-3">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  Nora Silvester
                  <span class="float-right text-sm text-warning"><i class="fa fa-star"></i></span>
                </h3>
                <p class="text-sm">The subject goes here</p>
                <p class="text-sm text-muted"><i class="fa fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item dropdown-footer">See All Messages</a>
        </div>
      </li>
      <!-- Notifications Dropdown Menu -->
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="fa fa-bell"></i>
          <span class="badge badge-warning navbar-badge">15</span>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <span class="dropdown-item dropdown-header">15 Notifications</span>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fa fa-envelope mr-2"></i> 4 new messages
            <span class="float-right text-muted text-sm">3 mins</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fa fa-users mr-2"></i> 8 friend requests
            <span class="float-right text-muted text-sm">12 hours</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fa fa-file mr-2"></i> 3 new reports
            <span class="float-right text-muted text-sm">2 days</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-widget="fullscreen" href="#" role="button">
          <i class="fa fa-expand-arrows-alt"></i>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button">
          <i class="fa fa-th-large"></i>
        </a>
      </li>
    </ul>
</nav>

resources/views/layouts/admin-panel/partials/_sidebar.blade.php
 <!-- Main Sidebar Container -->
 <aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="index3.html" class="brand-link text-center">
      <span class="brand-text font-weight-light text-center">Cash Your Trash</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user panel (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
          <img src="{{asset('dist/img/user2-160x160.jpg')}}" class="img-circle elevation-2" alt="User Image">
        </div>
        <div class="info">
          <a href="#" class="d-block">{{auth()->user()->name}}</a>
        </div>
      </div>



      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
        @if (auth()->user()->isAdmin())
        <li class="nav-item">
            <a href="{{route('employees.create-basic')}}" class="nav-link">
                <i class="nav-icon fa fa-plus"></i>
                <p>
                    Add New Employee
                </p>
            </a>
        </li>
        <li class="nav-item">
            <a href="{{route('employees.index')}}" class="nav-link">
                <i class="nav-icon fa fa-eye"></i>
                <p>
                    View All Employees
                </p>
            </a>
        </li>
        <li class="nav-item">
            <a href="{{route('trashes.pending')}}" class="nav-link">
              <i class="nav-icon fa fa-plus"></i>
              <p>
                Trash Pending
              </p>
            </a>
          </li>
        @endif
        @if (auth()->user()->isEmployee())
            <li class="nav-item">
                <a href="{{route('trashes.assigned')}}" class="nav-link">
                <i class="nav-icon fa fa-plus"></i>
                <p>
                    Assigned Bookings
                </p>
                </a>
            </li>
        @endif

          <li class="nav-item">
            <a href="pages/widgets.html" class="nav-link">
              <i class="nav-icon fa fa-plus"></i>
              <p>
                New Booking
              </p>
            </a>
          </li>
          <li class="nav-item">
            <a href="{{route('trashes.index')}}" class="nav-link">
              <i class="nav-icon fa fa-clock-o"></i>
              <p>
                Booking History
              </p>
            </a>
          </li>
          <li class="nav-item">
            <a href="pages/widgets.html" class="nav-link">
              <i class="nav-icon fa fa-th"></i>
              <p>
                Trash
              </p>
            </a>
          </li>
          <li class="nav-item">
            <a href="{{route('trashes.create')}}" class="nav-link">
              <i class="nav-icon fa fa-th"></i>
              <p>
                Create-Trash
              </p>
            </a>
          </li>
          <li class="nav-item">
            <a href="{{route('addresses.index')}}" class="nav-link">
              <i class="nav-icon fa fa-th"></i>
              <p>
                Address
              </p>
            </a>
          </li>
          <li class="nav-item">
            <a href="{{route('addresses.create')}}" class="nav-link">
              <i class="nav-icon fa fa-th"></i>
              <p>
                Create-Address
              </p>
            </a>
          </li>
          <li class="nav-item">
            <form action="{{route('logout')}}" method="POST">
                @csrf
                <button id="logout-btn" type="submit"><i class="fa fa-sign-out "></i> Logout</button>
            </form>
          </li>
        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>