routes/web.php
<?php

use App\Http\Controllers\AddressController;
use App\Http\Controllers\EmployeeController;
use App\Http\Controllers\TrashController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::middleware(['auth','admin'])->group(function(){
    Route::get('employees/create-basic',[EmployeeController::class,'create_basic'])->name('employees.create-basic');
    Route::get('employees/create-address',[EmployeeController::class,'create_address'])->name('employees.create-address');
    Route::get('employees/create-post',[EmployeeController::class,'create_post'])->name('employees.create-post');

    Route::post('employees/store-basic',[EmployeeController::class,'store_basic'])->name('employees.store-basic');
    Route::post('employees/store-address',[EmployeeController::class,'store_address'])->name('employees.store-address');
    Route::resource('employees', EmployeeController::class)->except('create');
    Route::get('trashes/pending', [TrashController::class,'adminPending'])->name('trashes.pending');
    Route::put('trashes/assign/{trash}', [TrashController::class,'adminAssign'])->name('trashes.assign');
});
Route::middleware(['auth','employee'])->group(function(){
    Route::get('trashes/assigned',[TrashController::class,'assigned'])->name('trashes.assigned');
    Route::put('trashes/picked/{trash}',[TrashController::class,'picked'])->name('trashes.picked');
    Route::put('trashes/reject/{trash}',[TrashController::class,'reject'])->name('trashes.reject');
});
Route::middleware(['auth'])->group(function(){

    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
    Route::resource('trashes', TrashController::class);
    Route::resource('addresses', AddressController::class);

});

app/Models/Trash.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;


class Trash extends Model
{
    use HasFactory;
    //constants
    const BOOKED = 'booked';
    const ASSIGNED = 'assigned';
    const PICKED = 'picked';
    const REJECT = 'reject';

    protected $guarded = ['id'];
    public function collecting_point()
    {
        return $this->belongsTo(Address::class,'address_id');
    }
    public function collecting_address()
    {
        return $this->collecting_point->address." ".$this->collecting_point->city." ".$this->collecting_point->postal_code;
    }
    public function getCollectingPersonInfo()
    {
        if($this->assigned_to == null)
            return "-";
        return $this->getAssignedEmployee()->loginDetails->name;
    }
    public function getWeightInfo()
    {
        if($this->weight == 0)
            return "-";
        return $this->weight;
    }
    public function getAssignedEmployee()
    {
        return Employee::find($this->assigned_to);
    }

    //scopes
    public function scopeAddress($query)
    {
        return $query->join('addresses',function($join)
        {
            $join->on('trashes.address_id','=','addresses.id');
        });
    }
    public function scopeUserTrashes($query)
    {
        return $query->where('user_id','=',auth()->id());
    }
    public function scopePending($query)
    {
        return $query->where('status','=',Trash::BOOKED);
    }
    public function scopeAssigned($query)
    {
        return $query->where('status','=',Trash::ASSIGNED)->where('assigned_to','=',User::getEmployeeId(auth()->id()));

    }
}

app/Http/Controllers/TrashController.php
<?php

namespace App\Http\Controllers;


use App\Http\Requests\trash\CreateTrashPickedRequest;
use App\Http\Requests\trash\CreateTrashRequest;
use App\Models\Address;
use App\Models\Employee;
use App\Models\Trash;
use Illuminate\Http\Request;

class TrashController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if(auth()->user()->isAdmin())
        {
            $trashes = Trash::address()->get();
        }
        else
        {
            $trashes = Trash::address()->userTrashes()->get();
        }
        return view('trash.index',compact('trashes'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $addresses = Address::ofUser()->get();
        return view('trash.create',compact('addresses'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateTrashRequest $request)
    {
        Trash::create([
            'address_id' => $request->address_id,
            'type' => $request->type,
            'status' => 'booked'
        ]);
        return redirect(route('trashes.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Trash  $trash
     * @return \Illuminate\Http\Response
     */
    public function show(Trash $trash)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Trash  $trash
     * @return \Illuminate\Http\Response
     */
    public function edit(Trash $trash)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Trash  $trash
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Trash $trash)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Trash  $trash
     * @return \Illuminate\Http\Response
     */
    public function destroy(Trash $trash)
    {
        //
    }
    public function adminPending()
    {
        $trashes = Trash::pending()->get();
        $employees = Employee::all();
        return view('trash.assign',compact('trashes','employees'));

    }
    public function adminAssign(Request $request,Trash $trash)
    {
        $trash->update([
            'assigned_to' => $request->assign,
            'status' => Trash::ASSIGNED

        ]);
        return redirect()->back();

    }
    public function assigned()
    {

        $trashes = Trash::assigned()->get();

        return view('trash.assigned',compact('trashes'));
    }
    public function picked(Request $request,Trash $trash)
    {
        $request->validate([
            'weight' => 'required'
        ]);
        $trash->update([
            'weight' => $request->weight,
            'status' => Trash::PICKED
        ]);
        return redirect()->back();
    }
    public function reject(Trash $trash)
    {
        $trash->update([
            'status' => Trash::REJECT
        ]);
        return redirect()->back();
    }
}

resources/views/trash/assign.blade.php
@extends('layouts.admin-panel.app')
@section('content')
<div class="content-wrapper">
    {{-- modal for assigning pickup --}}
    <div class="modal fade" id="assignModal">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h4 class="modal-title">Assign Pickup</h4>
            </div>
            <div class="modal-body">
                <form action="" id="assignForm" method="POST">
                    @csrf
                    @method('PUT')
                    <label for="assign">Assign Pickup to:</label>
                    <select  id="assign" value="Assign pickup to" name="assign">
                      @foreach ($employees as $employee)
                          <option value="{{$employee->id}}">{{$employee->loginDetails->name}}</option>
                      @endforeach
                    </select>
                  </div>
                  <div class="modal-footer justify-content-between">

                    {{-- <a href="{{route('trashes.assign')}}" class="btn btn-primary">Assign</a> --}}
                    <button type="submit" class="btn btn-primary">
                        Assign
                    </button>
                  </div>
                </form>

    </div>
        </div>
    </div>
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Trash</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Trash</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-12">
            <div class="card">
              <div class="card-header">
                <h3 class="card-title">Details</h3>
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                <table id="example2" class="table table-bordered table-hover">
                  <thead>
                  <tr>
                    <th>Collecting From</th>
                    <th>Type</th>
                    <th>Weight</th>
                    <th>Status</th>
                    <th>Collecting Person</th>
                    @if (auth()->user()->isAdmin())
                        <th>Actions</th>
                    @endif
                    <th></th>
                  </tr>
                  </thead>
                  <tbody>
                    @foreach ($trashes as $trash)
                        <tr>

                            <td>{{$trash->collecting_address()}}</td>
                            <td>{{$trash->type}}</td>
                            <td>{{$trash->getWeightInfo()}}</td>
                            <td>{{$trash->status}}</td>
                            <td> {{$trash->getCollectingPersonInfo()}}</td>
                            @if (auth()->user()->isAdmin())
                                <td> <button type="button" class="btn btn-success" onclick="assignForm({{$trash->id}})" data-toggle="modal" data-target="#assignModal" >
                                    Assign
                                  </button></td>
                                {{-- <td> {{$trash->getCollectingPersonInfo()}}</td> --}}
                            @endif

                        </tr>
                    @endforeach
                  </tbody>
                </table>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->

          </div>
          <!-- /.col -->
        </div>
        <!-- /.row -->
      </div>
      <!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>
@endsection
@section('page-level-scripts')
<script>
    function assignForm(trashId)
    {
        var url = "/trashes/assign/"+trashId;
        $("#assignForm").attr('action',url);
    }
</script>

@endsection

resources/views/trash/assigned.blade.php
@extends('layouts.admin-panel.app')
@section('content')
<div class="content-wrapper">
    {{-- modal for assigning pickup --}}
    <div class="modal fade" id="insertWeight">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h4 class="modal-title">Insert Weight</h4>
            </div>
            <div class="modal-body">
                <form action="" id="weightForm" method="POST">
                    @csrf
                    @method('PUT')
                    <label for="weight">
                        Weight:
                    </label>
                    <input type="number" name="weight">

                  </div>
                  <div class="modal-footer justify-content-between">

                    {{-- <a href="{{route('trashes.assign')}}" class="btn btn-primary">Assign</a> --}}
                    <button type="submit" class="btn btn-primary">
                        Submit
                    </button>
                  </div>
                </form>
            </div>
        </div>
    </div>
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Trash</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Trash</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-12">
            <div class="card">
              <div class="card-header">
                <h3 class="card-title">Details</h3>
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                <table id="example2" class="table table-bordered table-hover">
                  <thead>
                  <tr>
                    <th>Collecting From</th>
                    <th>Type</th>
                    <th>Weight</th>
                    <th>Actions</th>
                  </tr>
                  </thead>
                  <tbody>
                    @foreach ($trashes as $trash)
                        <tr>

                            <td>{{$trash->collecting_address()}}</td>
                            <td>{{$trash->type}}</td>
                            <td>{{$trash->getWeightInfo()}}</td>
                            <td><button class="btn btn-success" onclick="insertWeightForm({{$trash->id}})" data-toggle="modal" data-target="#insertWeight">
                                    Picked
                                </button>
                                <form action="{{route('trashes.reject',$trash->id)}}" method="POST">
                                    @csrf
                                    @method('PUT')
                                  <button type="submit" class="btn btn-danger" >
                                        Reject
                                  </button>
                                </form>

                            </td>

                        </tr>
                    @endforeach
                  </tbody>
                </table>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->

          </div>
          <!-- /.col -->
        </div>
        <!-- /.row -->
      </div>
      <!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>

@endsection
@section('page-level-scripts')
<script>
function insertWeightForm(trashId)
    {
        var url = "/trashes/picked/"+trashId;
        $("#weightForm").attr('action',url);
    }
</script>
@endsection

resources/views/trash/create.blade.php
@extends('layouts.admin-panel.app')
@section('page-level-styles')
<link rel="stylesheet" href="../../plugins/select2/css/select2.min.css">
<link rel="stylesheet" href="../../plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css">
<style>
    .btn-default
    {
        display: none;
    }
</style>
@endsection
@section('content')
@if(count($addresses)<1)

<button type="button" class="btn btn-default" data-toggle="modal" data-target="#modal-default" data-backdrop="static">
    Launch Default Modal
  </button>
<div class="modal fade" id="modal-default">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h4 class="modal-title">Add Address</h4>
        </div>
        <div class="modal-body">
          <p>Seems Like You Didnt Added Your Address Yet</p>

        </div>
        <div class="modal-footer justify-content-between">

          <a href="{{route('addresses.create')}}" class="btn btn-primary">Add Address</a>
        </div>
</div>
@else
@extends('layouts.admin-panel.app')
@section('content')
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Trash Pickup Booking</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Booking</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <!-- left column -->
          <div class="col-md-12">
            <!-- jquery validation -->
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Create Booking</h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <form action="{{route('trashes.store')}}" method="POST" id="quickForm">
                @csrf
                @method('POST')
                <div class="card-body">
                    <div class="form-group">
                        <label for="post">Address</label>
                        <select class="form-control select2" name="address_id" style="width: 100%;">
                            @foreach ($addresses as $address )
                                <option value="{{$address->id}}">{{$address->address}}</option>
                            @endforeach
                          </select>
                    </div>

                    <div class="form-group">
                        <label for="post">Trash Type</label>
                        <select class="form-control select2" name="type" style="width: 100%;">
                            <option value="dry">Dry</option>
                            <option value="wet">wet</option>
                        </select>
                    </div>
                </div>
                <!-- /.card-body -->
                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Submit</button>
                </div>
              </form>
            </div>
            <!-- /.card -->
            </div>
          <!--/.col (left) -->
          <!-- right column -->
          <div class="col-md-6">

          </div>
          <!--/.col (right) -->
        </div>
        <!-- /.row -->
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>
@endsection

@endif
@endsection
@section('page-level-scripts')
<script>
    var element = document.getElementsByClassName("btn-default");
    if(element != null)
    {
        element[0].click();
    }
</script>
@endsection

resources/views/trash/index.blade.php
@extends('layouts.admin-panel.app')
@section('content')
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Trash</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Trash</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-12">
            <div class="card">
              <div class="card-header">
                <h3 class="card-title">Details</h3>
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                <table id="example2" class="table table-bordered table-hover">
                  <thead>
                  <tr>
                    <th>Collecting From</th>
                    <th>Type</th>
                    <th>Weight</th>
                    <th>Status</th>
                    <th>Collecting Person</th>
                  </tr>
                  </thead>
                  <tbody>
                    @foreach ($trashes as $trash)
                        <tr>

                            <td>{{$trash->collecting_address()}}</td>
                            <td>{{$trash->type}}</td>
                            <td>{{$trash->getWeightInfo()}}</td>
                            <td>{{$trash->status}}</td>
                            <td> {{$trash->getCollectingPersonInfo()}}</td>
                        </tr>
                    @endforeach
                  </tbody>
                </table>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->

          </div>
          <!-- /.col -->
        </div>
        <!-- /.row -->
      </div>
      <!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>
@endsection